# Generated by Django 5.0 on 2024-01-15 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_rename_tags_post_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("title",),
                "verbose_name": "тег(и)",
                "verbose_name_plural": "теги",
            },
        ),
    ]
