# Generated by Django 5.0 on 2024-01-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo_caption",
            field=models.TextField(
                blank=True, null=True, verbose_name="описание картинки"
            ),
        ),
    ]
