# Generated by Django 5.0 on 2024-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_photo_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(
                default=True,
                verbose_name="опубликовано",
            ),
        ),
    ]
