# Generated by Django 5.0.1 on 2024-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_post_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="добавлен"),
                ),
            ],
            options={
                "verbose_name": "подписчик(а)",
                "verbose_name_plural": "подписчики",
                "ordering": ("-created_at",),
            },
        ),
    ]
