name: ScienceNews Deploy

on:
  workflow_run:
    workflows: ["ScienceNews Testing"]
    types:
      - completed
    dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Connect to VPS over SSH
#        uses: appleboy/ssh-action@master
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PATH }}
            ./deploy.sh
